#!/bin/bash

banner()
{
  echo "+------------------------------------------------------------+"
  printf "| %-58s | \n" " `date`"
  echo "|                                                            |"
  printf "|`tput bold` %-58s `tput sgr0`|\n" "$@ "
  echo "+------------------------------------------------------------+"
}
banner \ "Welcome to Tormesbot. Please ensure you have all the" \ "files needed to run tormes inside the folder you ran this" \ "script from. Required files are sample1_R1.fastq.gz," \ "sample1_R2.fastq.gz. If you also have a " \ "reference_genome_file.fasta please include it in this" \ "folder. You can run more than one sample at a time." \ "Tormes works better with multiple samples."
ranbot=torm$((1 + RANDOM % 1000))
mkdir $ranbot
function banner2 ()
{
  echo "+------------------------------------------------------------+"
  printf "|`tput bold` %-58s `tput sgr0`|\n" "$@ "
  echo "+------------------------------------------------------------+"
}
banner2 "Tango Connectivity and HPC Notification Information"
echo
read -p "Please enter your email address: " emailvar
echo
read -p "Please enter your tango username: " uservar
echo
banner2 "Tormes minimum required information "
echo
echo "Tormes will create a folder for your output,"
read -p "what would you like this folder to be called?: " outputfolvar
echo -e "Samples\t""Read1\t""Read2\t""Description" >> samples_metadata.txt
plogpoop=y
while [[ "$plogpoop" =~ ^([yY][eE][sS]|[yY])+$ ]]; do
r1check=(*R1.fastq.gz)
r2check=(*R2.fastq.gz)
if [[ -f "$r1check" && -f "$r2check" ]] ; then
for butts in ${!r1check[*]}; do
echo -e "${r1check[$butts]:0:7}""\t""${r1check[$butts]}""\t""${r2check[$butts]}""\t""${r1check[$butts]:0:7}" >> samples_metadata.txt
plogpoop=n
done
else
read -r -p "Either forward or reverse reads are not present in the folder this script ran from. Please move R1 and R2 files into this folder then select y when finished. Select n to quit script. [y/n]: " diarrhea
if [[ "$diarrhea" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
		continue
		else
		echo
		echo "Live long and prosper."
		echo
		exit 0
fi
fi
done
# for stench in ${!r1check[*]}; do
# cp ${r1check[$stench]} $ranbot
# done
# for splash in ${!r2check[*]}; do
# cp ${r2check[$splash]} $ranbot
# done
mv samples_metadata.txt $ranbot

echo "#!/bin/bash -i" >> slurm.sub
echo "#SBATCH --job-name=$ranbot" >> slurm.sub
echo "#SBATCH --mail-type=ALL" >> slurm.sub
echo "#SBATCH --mail-user=$emailvar" >> slurm.sub
echo "#SBATCH --partition=tango" >> slurm.sub
echo "#SBATCH --ntasks=28" >> slurm.sub
echo "#SBATCH --mem=250G" >> slurm.sub
echo "#SBATCH --time=96:00:00" >> slurm.sub
echo echo Running on host \`hostname\` >> slurm.sub
echo echo Time is \`date\` >> slurm.sub
echo "module load miniconda" >> slurm.sub
echo "source activate tormes-1.0" >> slurm.sub
dogpoop=y
while [[ "$dogpoop" =~ ^([yY][eE][sS]|[yY])+$ ]] ; do
refcheck=$(ls *".fasta")
if [ -f "$refcheck" ]; then
echo "tormes -m /scratch/$uservar/$ranbot/samples_metadata.txt -o $outputfolvar -t 28 -r /scratch/$uservar/$ranbot/$refcheck" >> slurm.sub
cp "$refcheck" $ranbot
dogpoop=n
else
read -r -p "No reference genome detected (filename.fasta) If you would like to include a reference genome,please move the '.fasta' file into the folder that you ran this script from and then choose 'y' [y/n]: " brown
			if [[ "$brown" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
			continue
			else
			echo "tormes -m /scratch/$uservar/$ranbot/samples_metadata.txt -o $outputfolvar -t 28" >> slurm.sub
			dogpoop=n
fi
fi
done

chmod +x slurm.sub
mv slurm.sub $ranbot

echo
banner2 "Tormesbot has created a folder called $ranbot and moved" \ "all of your files into it. Tormesbot will now transfer" \ "the folder and its contents to your Tango /scratch/$uservar/" \ "After the files have been copied to Tango, Tormesbot will" \ "run Tormes."

read -n 1 -s -r -p "Please press any key to continue..... " lol

home=`pwd`
sftp $uservar@tango.unisa.edu.au <<EOF
cd /scratch/$uservar
put -r $home/$ranbot
exit
EOF

# ssh -t $uservar@tango.unisa.edu.au "cd /scratch/$uservar/$ranbot; sbatch slurm.sub; exit"
echo
banner2 " !!!IMPORTANT!!!" \ "Upon completion you will receive an email from the HPC." \ "If you would like Tormesbot to retrieve your files," \ "please execute the script 'tormesretrieve' in the folder " \ "where you ran tormesbot from when you have received" \ "the completion email." 
echo
echo "#!/bin/bash" >> tormesretrieve
echo "sftp $uservar@tango.unisa.edu.au <<EOF" >> tormesretrieve
echo "cd /scratch/$uservar" >> tormesretrieve
echo "rm $ranbot/*.fastq.gz" >> tormesretrieve
echo "get -a -r $ranbot" >> tormesretrieve
echo "exit" >> tormesretrieve
echo "EOF" >> tormesretrieve
echo "ssh $uservar@tango.unisa.edu.au <<EOF" >> tormesretrieve
echo "rm -r /scratch/$uservar/$ranbot/$outputfolvar" >> tormesretrieve
echo "rm -r /scratch/$ranbot" >> tormesretrieve
echo "exit" >> tormesretrieve
echo "EOF" >> tormesretrieve
echo "rm $ranbot/*.fastq.gz" >> tormesretrieve
echo "mv $ranbot/slurm* $ranbot/$outputfolvar/" >> tormesretrieve
echo "mv $ranbot/*.fasta $ranbot/$outputfolvar/" >> tormesretrieve
echo "mv $ranbot/samples_metadata.txt $ranbot/$outputfolvar/" >> tormesretrieve
echo "mv $ranbot/$outputfolvar ." >> tormesretrieve
echo "rm -r $ranbot" >> tormesretrieve
echo "echo '("Your files have been retrieved, they are located in the folder named $outputfolvar")'" >> tormesretrieve
echo "echo" >> tormesretrieve
chmod +x tormesretrieve
echo
banner2 " It has been tormesbot's pleasure to assist" \ "you with all your whole genome sequencing needs." \ "Have a nice day."
echo
echo 
exit
